GROUP_ID=com.jlj.kuiklybase
MAVEN_VERSION=0.0.1
KOTLIN_VERSION_LIST=2.1.21
OHOS_KOTLIN_VERSION_LIST=2.0.21-ohos
MAVEN_REPO_URL=https://mirrors.tencent.com/repository/maven/kuikly-open/
MAVEN_USERNAME=
MAVEN_PASSWORD=
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.native.ignoreDisabledTargets=true
android.useAndroidX=true
